import 'package:flutter/material.dart';
import 'package:weather_app/core/helper_function/build_page.dart'; // Importing your helper function for building pages
import 'package:weather_app/core/utiles/app_color.dart'; // Importing your color utility

class CustomBottomNavigationBar extends StatefulWidget {
  const CustomBottomNavigationBar({super.key});

  @override
  State<CustomBottomNavigationBar> createState() => _CustomBottomNavigationBarState();
}

class _CustomBottomNavigationBarState extends State<CustomBottomNavigationBar> {
  int _selectedIndex = 0; // Track the selected index

  // Method to handle page navigation when a BottomNavigationBar item is selected
  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index; // Update the index to the selected page
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const SizedBox(height: 30),
        // Body: Display pages using IndexedStack based on the selected index
        Expanded(
          child: IndexedStack(
            index: _selectedIndex, // Shows the currently selected page
            children: buildPages(context), // Pages are generated by your buildPages helper
          ),
        ),
        // BottomNavigationBar
        BottomNavigationBar(
          currentIndex: _selectedIndex, // Highlight the current selected tab
          type: BottomNavigationBarType.fixed,
          backgroundColor: AppColor.PrimaryHomeColor, // Use your app's primary color
          selectedItemColor: Colors.white, // Set selected item color
          unselectedItemColor: Colors.white54, // Set unselected item color
          showSelectedLabels: false, // Hide labels for selected items
          showUnselectedLabels: false, // Hide labels for unselected items
          onTap: _onItemTapped, // Handle tap on navigation bar
          items: const [
            BottomNavigationBarItem(
              icon: Icon(Icons.sunny), // Icon for the Weather page
              label: 'Weather',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.star), // Icon for the Favorites page
              label: 'Favorites',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.check), // Icon for the Check page
              label: 'Check',
            ),
          ],
        ),
      ],
    );
  }
}
